# -*- coding: utf-8 -*-
"""Customer Growth Copilot - Interactive Dashboard

Automatically generated by Colab.
Original file is located at:
    https://colab.research.google.com/drive/1fI0P_LuAaNyOAIsE7dUZwiPR6M3eX9ol
"""

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from sklearn.preprocessing import MinMaxScaler

# ── PAGE CONFIG (MUST BE FIRST) ───────────────────────────────────────────────
st.set_page_config(
    page_title="Customer Growth Copilot",
    page_icon="🛍️",
    layout="wide"
)

st.markdown("""
<style>
    .metric-card {
        background: #1e1e2e; border-radius: 12px;
        padding: 20px; text-align: center; border-left: 4px solid;
    }
    .metric-value { font-size: 2rem; font-weight: 700; }
    .metric-label { font-size: 0.85rem; color: #aaa; margin-top: 4px; }
    .action-box {
        background: #1e1e2e; border-radius: 10px;
        padding: 14px 18px; margin-bottom: 10px; border-left: 4px solid;
    }
</style>
""", unsafe_allow_html=True)

SEG_COLORS = {'VIP': '#2ecc71', 'Healthy': '#3498db', 'At Risk': '#f39c12', 'Critical': '#e74c3c'}
SEG_ORDER  = ['VIP', 'Healthy', 'At Risk', 'Critical']


# ── STEP 1: load & clean (cached) ─────────────────────────────────────────────
@st.cache_data
def load_data(file) -> pd.DataFrame:
    if file is None: # Added check for None file
        return pd.DataFrame() # Return empty DataFrame if no file
    df = pd.read_csv('customer_shopping_behavior.csv')
    df.columns = df.columns.str.lower().str.replace(' ', '_')

    # Rename purchase amount column regardless of whether it has (usd) suffix
    df.columns = [c.replace('(usd)', '').strip().replace(' ', '_') for c in df.columns]
    amt_col = [c for c in df.columns if 'purchase_amount' in c]
    if amt_col and amt_col[0] != 'purchase_amount':
        df = df.rename(columns={amt_col[0]: 'purchase_amount'})

    if 'promo_code_used' in df.columns:
        df = df.drop(columns=['promo_code_used'])

    df['review_rating'] = df.groupby('category')['review_rating'].transform(
        lambda x: x.fillna(x.median())
    )

    labels = ['Young Adult', 'Adult', 'Middle-Aged', 'Senior']
    df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)
    return df


# ── STEP 2: aggregate to customer level (cached) ──────────────────────────────
@st.cache_data
def build_customer_df(df: pd.DataFrame) -> pd.DataFrame:
    # Handle empty DataFrame gracefully
    if df.empty:
        return pd.DataFrame(columns=['customer_id', 'age', 'gender', 'age_group', 'avg_spend',
                                     'avg_rating', 'previous_purchases', 'subscription_status',
                                     'discount_usage_pct', 'score_purchases', 'score_spend',
                                     'score_rating', 'score_subscription', 'score_discount']) # Define expected columns

    cdf = df.groupby('customer_id').agg(
        age                = ('age',               'first'),
        gender             = ('gender',            'first'),
        age_group          = ('age_group',         'first'),
        avg_spend          = ('purchase_amount',   'mean'),
        avg_rating         = ('review_rating',     'mean'),
        previous_purchases = ('previous_purchases','max'),
        subscription_status= ('subscription_status','first'),
        discount_usage_pct = ('discount_applied',
                              lambda x: (x == 'Yes').mean() * 100)
    ).reset_index()

    # Normalized score components — created ONCE, stored as columns
    scaler = MinMaxScaler(feature_range=(0, 100))
    cdf['score_purchases']    = scaler.fit_transform(cdf[['previous_purchases']])
    cdf['score_spend']        = scaler.fit_transform(cdf[['avg_spend']])
    cdf['score_rating']       = scaler.fit_transform(cdf[['avg_rating']])
    cdf['score_subscription'] = cdf['subscription_status'].map({'Yes': 100, 'No': 0})
    cdf['score_discount']     = 100 - cdf['discount_usage_pct']
    return cdf


# ── STEP 3: apply weights → score + segment (NOT cached, cheap to rerun) ─────
SCORE_COLS = ['score_purchases', 'score_spend', 'score_rating',
              'score_subscription', 'score_discount']

def apply_weights(cdf: pd.DataFrame, weights: dict) -> pd.DataFrame:
    out = cdf.copy()
    if out.empty:
        return pd.DataFrame(columns=out.columns.tolist() + ['health_score', 'segment'])
    out['health_score'] = sum(
        out[col] * w for col, w in weights.items()
    ).round(1)
    out['segment'] = pd.cut(
        out['health_score'],
        bins=[-1, 25, 50, 75, 101],
        labels=['Critical', 'At Risk', 'Healthy', 'VIP']
    )
    return out


# ── SIDEBAR ─────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.image("https://img.icons8.com/fluency/96/shopping-bag.png", width=60)
    st.title("Customer Growth\nCopilot")
    st.markdown("---")

    uploaded = st.file_uploader("Upload CSV", type="csv")
    if not uploaded:
        st.info("Upload your `customer_shopping_behavior.csv` to get started.")
        # st.stop() # Removed st.stop() here as it doesn't fully halt execution in Colab

    # Load & build — these only rerun when the file changes
    raw_df     = load_data(uploaded)
    customer_df = build_customer_df(raw_df)

    st.markdown("### 🔍 Filters")

    # Conditionally render filters if customer_df is not empty
    if not customer_df.empty:
        sel_gender = st.multiselect("Gender",
            sorted(customer_df['gender'].unique()),
            default=sorted(customer_df['gender'].unique()))
        sel_age = st.multiselect("Age Group",
            list(customer_df['age_group'].cat.categories),
            default=list(customer_df['age_group'].cat.categories))
        sel_sub = st.multiselect("Subscription",
            sorted(customer_df['subscription_status'].unique()),
            default=sorted(customer_df['subscription_status'].unique()))
    else: # Provide default empty lists if no data
        sel_gender = []
        sel_age = []
        sel_sub = []

    st.markdown("---")
    st.markdown("### ⚖️ Score Weights")
    st.caption("Drag to adjust — scores recalculate instantly.")
    w = {
        'score_purchases':    st.slider("Previous Purchases", 0, 100, 30),
        'score_spend':        st.slider("Avg Spend",          0, 100, 25),
        'score_rating':       st.slider("Review Rating",      0, 100, 20),
        'score_subscription': st.slider("Subscription",       0, 100, 15),
        'score_discount':     st.slider("Discount (inverted)",0, 100, 10),
    }
    total_w = sum(w.values())
    if total_w == 0:
        st.warning("At least one weight must be > 0.")
        # st.stop() # Removed st.stop() here
        normalized_weights = {col: 0 for col in SCORE_COLS} # Provide zero weights
    else:
        normalized_weights = {col: val / total_w for col, val in w.items()}

    st.markdown("---")
    sel_seg = st.multiselect("Segment", SEG_ORDER, default=SEG_ORDER)


# ── SCORE & FILTER ──────────────────────────────────────────────────────────────
# apply_weights is fast (no I/O) so no caching needed
scored_df = apply_weights(customer_df, normalized_weights)

# Conditionally filter if scored_df is not empty
if not scored_df.empty:
    fdf = scored_df[
        scored_df['gender'].isin(sel_gender) &
        scored_df['age_group'].isin(sel_age) &
        scored_df['subscription_status'].isin(sel_sub) &
        scored_df['segment'].isin(sel_seg)
    ].copy()
else:
    fdf = pd.DataFrame(columns=scored_df.columns) # Ensure fdf is an empty DataFrame with columns


# Only display the rest of the app if fdf is not empty
if not fdf.empty:
    # ── HEADER ────────────────────────────────────────────────────────────────────
    st.title("🛍️ Customer Growth Copilot")
    st.caption(f"Showing **{len(fdf):,}** of {len(scored_df):,} customers · Adjust filters & weights in the sidebar")
    st.markdown("---")


    # ── KPI CARDS ─────────────────────────────────────────────────────────────────
    def kpi(col, val, label, color):
        col.markdown(f"""
        <div class="metric-card" style="border-color:{color}">
            <div class="metric-value" style="color:{color}">{val}</div>
            <div class="metric-label">{label}</div>
        </div>""", unsafe_allow_html=True)

    k1, k2, k3, k4, k5 = st.columns(5)
    kpi(k1, f"{len(fdf):,}",                               "Total Customers",    "#3498db")
    kpi(k2, f"{fdf['health_score'].mean():.1f}",            "Avg Health Score",   "#9b59b6")
    kpi(k3, f"{(fdf['segment']=='VIP').sum():,}",            "VIP Customers",      "#2ecc71")
    kpi(k4, f"{(fdf['segment']=='Critical').sum():,}",       "Critical Customers", "#e74c3c")
    kpi(k5, f"${fdf['avg_spend'].mean():.0f}",               "Avg Spend / Visit",  "#f39c12")
    st.markdown("<br>", unsafe_allow_html=True)


    # ── ROW 1: DONUT + HISTOGRAM ──────────────────────────────────────────────────
    c1, c2 = st.columns([1, 1.6])

    with c1:
        st.subheader("Segment Distribution")
        seg_counts = (fdf['segment']
                      .value_counts()
                      .reindex(SEG_ORDER)
                      .fillna(0))
        fig_pie = go.Figure(go.Pie(
            labels=seg_counts.index, values=seg_counts.values,
            hole=0.55,
            marker_colors=[SEG_COLORS[s] for s in seg_counts.index],
            textinfo='label+percent'
        ))
        fig_pie.update_layout(
            showlegend=False, margin=dict(t=10, b=10, l=10, r=10),
            paper_bgcolor='rgba(0,0,0,0)', font_color='white', height=300
        )
        st.plotly_chart(fig_pie, use_container_width=True)

    with c2:
        st.subheader("Health Score Distribution")
        fig_hist = px.histogram(
            fdf, x='health_score', nbins=40,
            color='segment', color_discrete_map=SEG_COLORS,
            category_orders={'segment': SEG_ORDER}
        )
        for thresh, seg in [(75, 'VIP'), (50, 'Healthy'), (25, 'At Risk')]:
            fig_hist.add_vline(x=thresh, line_dash='dash',
                               line_color=SEG_COLORS[seg],
                               annotation_text=seg,
                               annotation_font_color=SEG_COLORS[seg])
        fig_hist.update_layout(
            paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)',
            font_color='white', height=300, margin=dict(t=10),
            xaxis_title='Health Score', yaxis_title='# Customers'
        )
        st.plotly_chart(fig_hist, use_container_width=True)


    # ── ROW 2: SCATTER + BAR ──────────────────────────────────────────────────────
    c3, c4 = st.columns(2)

    with c3:
        st.subheader("Health Score vs Avg Spend")
        fig_sc = px.scatter(
            fdf, x='health_score', y='avg_spend',
            color='segment', color_discrete_map=SEG_COLORS,
            opacity=0.55,
            hover_data=['customer_id', 'previous_purchases', 'subscription_status'],
            category_orders={'segment': SEG_ORDER}
        )
        fig_sc.update_layout(
            paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)',
            font_color='white', height=320, margin=dict(t=10),
            xaxis_title='Health Score', yaxis_title='Avg Spend (USD)'
        )
        st.plotly_chart(fig_sc, use_container_width=True)

    with c4:
        st.subheader("Avg Spend & Rating by Segment")
        seg_agg = (fdf.groupby('segment', observed=True)
                   .agg(avg_spend=('avg_spend','mean'), avg_rating=('avg_rating','mean'))
                   .reindex(SEG_ORDER).reset_index())
        fig_bar = go.Figure()
        fig_bar.add_trace(go.Bar(
            name='Avg Spend ($)', x=seg_agg['segment'], y=seg_agg['avg_spend'],
            marker_color=[SEG_COLORS[s] for s in seg_agg['segment']], yaxis='y'
        ))
        fig_bar.add_trace(go.Scatter(
            name='Avg Rating', x=seg_agg['segment'], y=seg_agg['avg_rating'],
            mode='lines+markers', marker=dict(size=10, color='white'),
            line=dict(color='white', dash='dot'), yaxis='y2'
        ))
        fig_bar.update_layout(
            paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)',
            font_color='white', height=320, margin=dict(t=10),
            yaxis=dict(title='Avg Spend (USD)'),
            yaxis2=dict(title='Avg Rating', overlaying='y', side='right', range=[0, 5]),
            legend=dict(orientation='h', y=1.12)
        )
        st.plotly_chart(fig_bar, use_container_width=True)


    # ── ACTION MAP ────────────────────────────────────────────────────────────────
    st.markdown("---")
    st.subheader("📋 Recommended Actions by Segment")
    actions = {
        'VIP':      ('🏆', '#2ecc71', 'Exclusive loyalty rewards, early product access, VIP events'),
        'Healthy':  ('✅', '#3498db', 'Premium membership upsell, cross-sell campaigns, referral program'),
        'At Risk':  ('⚠️', '#f39c12', 'Re-engagement discounts, personalised recommendations, win-back email'),
        'Critical': ('🚨', '#e74c3c', 'Win-back campaign, churn survey, last-chance offer'),
    }
    for col, seg in zip(st.columns(4), SEG_ORDER):
        icon, color, action = actions[seg]
        count = (fdf['segment'] == seg).sum()
        pct   = count / len(fdf) * 100 if len(fdf) else 0
        col.markdown(f"""
        <div class="action-box" style="border-color:{color}">
            <div style="font-size:1.3rem">{icon} <strong style="color:{color}">{seg}</strong></div>
            <div style="font-size:1.5rem;font-weight:700;margin:6px 0">
                {count:,} <span style="font-size:0.85rem;color:#aaa">({pct:.1f}%)</span>
            </div>
            <div style="font-size:0.82rem;color:#ccc">{action}</div>
        </div>""", unsafe_allow_html=True)


    # ── CUSTOMER EXPLORER ──────────────────────────────────────────────────────────
    st.markdown("---")
    st.subheader("🔎 Customer Explorer")

    col_search, col_export = st.columns([3, 1])
    with col_search:
        search = st.text_input("Search by Customer ID", placeholder="e.g. 42")
    with col_export:
        st.markdown("<br>", unsafe_allow_html=True)
        csv_bytes = fdf.to_csv(index=False).encode()
        st.download_button("⬇️ Export filtered CSV", csv_bytes,
                           "customers_filtered.csv", "text/csv")

    display_cols = ['customer_id', 'age', 'gender', 'age_group', 'segment',
                    'health_score', 'avg_spend', 'avg_rating',
                    'previous_purchases', 'subscription_status', 'discount_usage_pct']

    tdf = (fdf[fdf['customer_id'].astype(str).str.contains(search)]
           if search else fdf)

    st.dataframe(
        tdf[display_cols].sort_values('health_score', ascending=False).reset_index(drop=True),
        use_container_width=True, height=320,
        column_config={
            'health_score':       st.column_config.ProgressColumn(
                                      "Health Score", min_value=0, max_value=100),
            'avg_spend':          st.column_config.NumberColumn("Avg Spend",   format="$%.0f"),
            'avg_rating':         st.column_config.NumberColumn("Avg Rating",  format="%.1f ⭐"),
            'discount_usage_pct': st.column_config.NumberColumn("Disc. Usage", format="%.0f%%"),
        }
    )

st.markdown("---")
st.caption("By: YESICA MAGNOLI · Customer Growth Copilot · Built with Streamlit & Plotly · Retail Sales Portfolio Project")
