#Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as Revenue
from customer
group by gender;

#Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, avg(purchase_amount) as avg from customer 
where discount_applied = 'Yes' 
and purchase_amount >= (select(avg(purchase_amount)));

#Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2)as avg_rating
from customer
group by item_purchased
order by avg_rating desc
limit 5;

#Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select avg(purchase_amount) as avg_purc_amount, shipping_type
from customer
where shipping_type in ("Express","Standard")
group by shipping_type;

#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select avg(purchase_amount) as avg_purc_amount, shipping_type
from customer
where shipping_type in ("Express","Standard")
group by shipping_type;

#Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select  item_purchased, 
round(100 * sum(case when discount_applied="Yes" then 1 else 0 end)/count(*),0)as times_disc_applied
from customer
group by item_purchased
order by times_disc_applied desc
LIMIT 5;

#Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
select 
case
	when previous_purchases <= 1 then "New"
    when previous_purchases between 2 and 10 then "Returning"
	else "Loyal"
end as customer_segment,
count(*) as customer_count
from customer
group by customer_segment
order by customer_count desc;

#Q8. What are the top 3 most purchased products within each category? 
select item_purchased,category,
 count(*) as qty 
from customer
group by category, item_purchased
order by qty desc;

#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeted_clients
from customer
where previous_purchases > 5
group by subscription_status;

#Q10. What is the revenue contribution of each age group? 
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;