# -*- coding: utf-8 -*-
"""retail_sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-uLo9PbIghNwKtu5Gp06lSPkVAfeyEQ
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# The 'FileNotFoundError' indicates that the file 'customer_shopping_behavior.csv' was not found.
# Since Google Drive is mounted, the file is likely in your Drive.
# Update the path below to the correct location of your CSV file in Google Drive.
# For example, if it's directly in 'My Drive', the path would be '/content/drive/MyDrive/customer_shopping_behavior.csv'.
# If it's in a subfolder, e.g., 'data', it would be '/content/drive/MyDrive/data/customer_shopping_behavior.csv'.
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Business_Case_Retail-Sales/customer_shopping_behavior.csv')

df.head()

df.info()

"""describe "all" to get the summarize of both, numerical and categorical values"""

df.describe(include='all')

"""Let's check if there is any "null" values"""

df.isnull().sum()

"""Column 'Review Rating' has nulls. To replace them I'm going to use the the median within each category. It is important to notice that I am not usong the overall median value because this is affected by outliers whereas the category one do not have this bias."""

df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

df.isnull().sum()

"""I will modify all column's names into lowercase separeted by underscores"""

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

df.columns

#create a column 'age_group'

labels = ['Young Adult', 'Adult', 'Middle-Aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels= labels)

df[['age','age_group']].head()

df['frequency_of_purchases'].head()

# create column purchase_frequency_days

#first create a dictionary that maps each frequency in number of days in the column
frequency_mapping = {
'Fortnightly':14,
'Weekly':7,
'Monthly':30,
'Quarterly':90,
'Bi-Weekly':14,
'Annually':365,
'Every 3 Months':90

}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

df[['purchase_frequency_days','frequency_of_purchases']].head(10)

# i am going to check if the columns  'discount_applied' and 'promo_code_used' are equals and i have redundancy.
(df['discount_applied'] == df['promo_code_used']).all()

df = df.drop(columns=['promo_code_used'], axis=1)

pip install psycopg2-binary sqlalchemy

pip install --upgrade pip

"""#CREATE AN SQL DATABASE:

 I've created a separated file called "customer_behaviour_queries.sql" where I have created the database and have performed data exploration in MySQL.

"""

pip install --upgrade SQLAlchemy

#import sqlalchemy
#print(sqlalchemy.__version__)

# Commented out IPython magic to ensure Python compatibility.
# %pip install "SQLAlchemy<2.0"
# %pip install pymysql

#from sqlalchemy import create_engine

#Mysql connection
username = 'root'
password = '7899'
host = '127.0.0.1'
port= 3306
database = 'customer_behavior'


engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')

#Write the DataFrame to MySQL
table_name = "customer"
df.to_sql(table_name, con=engine, if_exists="replace", index=False)

#Read the data back from MySQL to verify
pd.read_sql(f'SELECT * FROM customer LIMIT 5', con=engine)

import pandas as pd
pd.read_sql(f'SELECT * FROM customer LIMIT 5', con=engine)

pd.read_sql(
    """
    select subscription_status,
        count(customer_id) AS total_customers,
        round(avg(purchase_amount),2) as avg_spend,
        sum(purchase_amount) as total_revenue
    from customer
    group by subscription_status
    order by total_revenue desc
    """,
    con=engine
)

#Q6. Which 5 products have the highest percentage of purchases with discounts applied?

pd.read_sql(
    """
    select subscription_status,
        count(customer_id) AS total_customers,
        round(avg(purchase_amount),2) as avg_spend,
        sum(purchase_amount) as total_revenue
    from customer
    group by subscription_status
    order by total_revenue desc
    """,
    con=engine
)

"""# **AI Product: Customer Growth Copilot**

User
* Marketing Manager
* CRM Manager
* E-commerce Manager

**Business Problem**

A retailer has 20,000 customers.
Marketing budget is limited.

Who should receive:

- discounts?
- loyalty offers?
- premium memberships?
- reactivation campaigns?

Let's solve the "guessing problem" of most companies

**KPI 1: Customer Health Score**

Based on:

* Previous purchases
* Subscription status
* Average spend
* Discount usage
* Review rating
"""

df.columns

#Create a sub dataset called 'customer_id' and then calculates the total number of purchases (count), the average purchase amount (mean),
#and the average review_rating for each unique customer.
#This helps to consolidate customer-level information
customer_df = df.groupby('customer_id').agg({
          'age': 'first',
          'gender': 'first',
          'purchase_amount': 'sum',
          'review_rating': 'mean',
          'previous_purchases': 'max',
          'subscription_status': 'first',
          'discount_applied': lambda x: (x == 'Yes').mean() * 100
      })

# First, ensure that 'customer_df = df.groupby(...).agg(...)' is run in cell YRpOGxHzq4e6.
# Then, flatten the MultiIndex columns before renaming.
customer_df.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in customer_df.columns.values]

customer_df.columns = [
    'age',
    'gender',
    'total_spend',
    'avg_rating',
    'previous_purchases',
    'subscription_status',
    'discount_usage_pct'
]

customer_df = customer_df.reset_index()

customer_df.head()

"""Customer Health Score (0–100) and create the segments:

* VIP
* Healthy
* At Risk
* Critical

# NORMALIZE COMPONENTS TO 0–100

Each variable lives on a different scale (purchases: 1–50, spend: $20–$100, rating: 2.5–5.0). Normalizing to 0–100 first makes the weighted sum meaningful.
"""

from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import seaborn as sns

scaler = MinMaxScaler(feature_range=(0, 100))

customer_df['score_purchases'] = scaler.fit_transform(
    customer_df[['previous_purchases']])

customer_df['score_spend'] = scaler.fit_transform(
    customer_df[['total_spend']])

customer_df['score_rating'] = scaler.fit_transform(
    customer_df[['avg_rating']])

# Subscription: binary 0 or 100
customer_df['score_subscription'] = customer_df['subscription_status'].map(
    {'Yes': 100, 'No': 0})

# Discount usage: INVERTED (lower dependency = healthier)
customer_df['score_discount'] = 100 - customer_df['discount_usage_pct']

# 2. WEIGHTED HEALTH SCORE

weights = {
    'score_purchases':    0.30,
    'score_spend':        0.25,
    'score_rating':       0.20,
    'score_subscription': 0.15,
    'score_discount':     0.10,
}

customer_df['health_score'] = sum(customer_df[col] * w for col, w in weights.items()).round(1)

# 3. SEGMENT LABELS

def assign_segment(score):
    if score >= 75:
        return 'VIP'
    elif score >= 50:
        return 'Healthy'
    elif score >= 25:
        return 'At Risk'
    else:
        return 'Critical'

customer_df['segment'] = customer_df['health_score'].apply(assign_segment)
customer_df.head()

# 4. QUICK VALIDATION

print("=== Segment Distribution ===")
print(customer_df['segment'].value_counts())
print()
print("=== Health Score Stats by Segment ===")
print(customer_df.groupby('segment')['health_score'].describe().round(2))
print()
print("=== Sample: Top 5 VIP Customers ===")
print(
    customer_df[customer_df['segment'] == 'VIP']
    .sort_values('health_score', ascending=False)
    [['customer_id', 'health_score', 'previous_purchases',
      'total_spend', 'avg_rating', 'subscription_status']]
    .head())

# 5. VISUALIZATIONS

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle('Customer Health Score Analysis', fontsize=14, fontweight='bold')

# 5a. Segment distribution (donut chart)
seg_counts = customer_df['segment'].value_counts()
colors = ['#2ecc71', '#3498db', '#f39c12', '#e74c3c']  # VIP, Healthy, At Risk, Critical
axes[0].pie(
    seg_counts,
    labels=seg_counts.index,
    autopct='%1.1f%%',
    colors=colors,
    wedgeprops={'width': 0.5},
    startangle=90
)
axes[0].set_title('Customer Segments')

# 5b. Health score distribution
axes[1].hist(customer_df['health_score'], bins=30, color='#3498db', edgecolor='white')
axes[1].axvline(75, color='#2ecc71', linestyle='--', label='VIP threshold')
axes[1].axvline(50, color='#f39c12', linestyle='--', label='At Risk threshold')
axes[1].axvline(25, color='#e74c3c', linestyle='--', label='Critical threshold')
axes[1].set_title('Health Score Distribution')
axes[1].set_xlabel('Health Score')
axes[1].set_ylabel('# Customers')
axes[1].legend(fontsize=8)

# 5c. Avg health score by segment + avg spend
seg_summary = customer_df.groupby('segment').agg(
    avg_health=('health_score', 'mean'),
    avg_spend=('total_spend', 'mean')
).reindex(['VIP', 'Healthy', 'At Risk', 'Critical'])

x = range(len(seg_summary))
bars = axes[2].bar(x, seg_summary['avg_health'], color=colors, edgecolor='white')
axes[2].set_xticks(x)
axes[2].set_xticklabels(seg_summary.index)
axes[2].set_title('Avg Health Score per Segment')
axes[2].set_ylabel('Avg Health Score')
for bar, spend in zip(bars, seg_summary['avg_spend']): # Changed 'total_spend' to 'avg_spend'
    axes[2].text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.5,
        f'${spend:.0f} avg',
        ha='center', fontsize=9
    )

plt.tight_layout()
plt.show()

# 6. BUSINESS ACTION MAPPING

action_map = {
    'VIP':      'Exclusive loyalty rewards + early access offers',
    'Healthy':  'Premium membership upsell + cross-sell campaigns',
    'At Risk':  'Re-engagement discounts + personalised recommendations',
    'Critical': 'Win-back campaign + survey to understand churn reasons',
}

print("\n=== Recommended Actions by Segment ===")
for seg, action in action_map.items():
    count = (customer_df['segment'] == seg).sum()
    print(f"  [{seg:8s}] ({count:4d} customers)  →  {action}")